### ISSUE TITLE
lsm-db fails to build on Centos 6.7 with gcc 4.4.7

### ISSUE THREAD

**Issue by abeusher** [coleifer/python-lsm-db#1]
**# python setup.py build**
running build
running build_ext
building 'lsm' extension
creating build
creating build/temp.linux-x86_64-2.6
creating build/temp.linux-x86_64-2.6/src
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fe                              xceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU                              _SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexce                              ptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SO                              URCE -fPIC -fwrapv -fPIC -I/usr/include/python2.6 -c lsm.c -o build/temp.linux-x                              86_64-2.6/lsm.o
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fe                              xceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU                              _SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexce                              ptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SO                              URCE -fPIC -fwrapv -fPIC -I/usr/include/python2.6 -c src/sqlite4.c -o build/temp                              .linux-x86_64-2.6/src/sqlite4.o
src/sqlite4.c: In function ‘pthreadMutexAlloc’:
src/sqlite4.c:15716: warning: initialization discards qualifiers from pointer ta                              rget type
src/sqlite4.c: In function ‘treeNextIsEndDelete’:
src/sqlite4.c:38247: warning: unused variable ‘rc’
src/sqlite4.c: In function ‘treePrevIsStartDelete’:
src/sqlite4.c:38269: warning: unused variable ‘rc’
src/sqlite4.c: In function ‘lsmTreeDelete’:
src/sqlite4.c:38695: warning: unused variable ‘iNode’
src/sqlite4.c: In function ‘lsmTreeCursorFlags’:
src/sqlite4.c:39082: warning: unused variable ‘rc’
src/sqlite4.c: In function ‘sqlite4OpenBtree’:
src/sqlite4.c:43465: warning: assignment from incompatible pointer type
src/sqlite4.c: At top level:
src/sqlite4.c:43505: error: redefinition of typedef ‘i64’
src/sqlite4.c:5237: note: previous declaration of ‘i64’ was here
src/sqlite4.c:43506: error: redefinition of typedef ‘u64’
src/sqlite4.c:5238: note: previous declaration of ‘u64’ was here
src/sqlite4.c:43507: error: redefinition of typedef ‘u32’
src/sqlite4.c:5239: note: previous declaration of ‘u32’ was here
src/sqlite4.c:43508: error: redefinition of typedef ‘u16’
src/sqlite4.c:5240: note: previous declaration of ‘u16’ was here
src/sqlite4.c:43509: error: redefinition of typedef ‘u8’
src/sqlite4.c:5242: note: previous declaration of ‘u8’ was here
src/sqlite4.c: In function ‘btCsrSeek’:
src/sqlite4.c:47783: warning: unused variable ‘pCell’
src/sqlite4.c: In function ‘assert_pages_used’:
src/sqlite4.c:52109: warning: unused variable ‘i’
src/sqlite4.c: In function ‘assert_schedule_page_used’:
src/sqlite4.c:52163: warning: unused variable ‘nPgPerBlk’
src/sqlite4.c: In function ‘btAllocatePage’:
src/sqlite4.c:52929: warning: unused variable ‘h’
src/sqlite4.c:52928: warning: unused variable ‘pp’
src/sqlite4.c: In function ‘sqlite4VdbeMemStringify’:
src/sqlite4.c:54376: warning: unused variable ‘fg’
src/sqlite4.c: In function ‘displayP4’:
src/sqlite4.c:56070: warning: pointer targets in passing argument 2 of ‘sqlite4B                              lobToHex’ differ in signedness
src/sqlite4.c:17633: note: expected ‘const u8 _’ but argument is of type ‘char \*                              ’
src/sqlite4.c: In function ‘sqlite4VdbeDecodeNumericKey’:
src/sqlite4.c:58872: warning: pointer targets in passing argument 3 of ‘sqlite4G                              etVarint64’ differ in signedness
src/sqlite4.c:19315: note: expected ‘sqlite4_uint64 *’ but argument is of type ‘                              sqlite4_int64 *’
src/sqlite4.c:58881: warning: pointer targets in passing argument 3 of ‘sqlite4G                              etVarint64’ differ in signedness
src/sqlite4.c:19315: note: expected ‘sqlite4_uint64 *’ but argument is of type ‘                              sqlite4_int64 *’
src/sqlite4.c:58889: warning: pointer targets in passing argument 3 of ‘sqlite4G                              etVarint64’ differ in signedness
src/sqlite4.c:19315: note: expected ‘sqlite4_uint64 *’ but argument is of type ‘                              sqlite4_int64 *’
src/sqlite4.c:58896: warning: pointer targets in passing argument 3 of ‘sqlite4G                              etVarint64’ differ in signedness
src/sqlite4.c:19315: note: expected ‘sqlite4_uint64 *’ but argument is of type ‘                              sqlite4_int64 *’
src/sqlite4.c: In function ‘decoderFromKey’:
src/sqlite4.c:58957: warning: pointer targets in passing argument 2 of ‘sqlite4V                              dbeMemSetStr’ differ in signedness
src/sqlite4.c:54763: note: expected ‘const char *’ but argument is of type ‘cons                              t KVByteArray *’
src/sqlite4.c:58963: warning: pointer targets in passing argument 2 of ‘sqlite4V                              dbeMemSetStr’ differ in signedness
src/sqlite4.c:54763: note: expected ‘const char *’ but argument is of type ‘cons                              t KVByteArray *’
src/sqlite4.c:58984: warning: pointer targets in passing argument 2 of ‘sqlite4V                              dbeMemSetStr’ differ in signedness
src/sqlite4.c:54763: note: expected ‘const char *’ but argument is of type ‘cons                              t KVByteArray *’
src/sqlite4.c:58989: warning: pointer targets in passing argument 2 of ‘sqlite4V                              dbeMemSetStr’ differ in signedness
src/sqlite4.c:54763: note: expected ‘const char *’ but argument is of type ‘cons                              t KVByteArray *’
src/sqlite4.c: In function ‘sqlite4VdbeExec’:
src/sqlite4.c:64369: warning: pointer targets in assignment differ in signedness
src/sqlite4.c:64450: warning: pointer targets in assignment differ in signedness
src/sqlite4.c: In function ‘sqlite4CodeSubselect’:
src/sqlite4.c:68963: warning: unused variable ‘iValToIns’
src/sqlite4.c: In function ‘hexFunc’:
src/sqlite4.c:79704: warning: unused variable ‘i’
src/sqlite4.c: In function ‘sqlite4InitOne’:
src/sqlite4.c:84258: warning: unused variable ‘zMasterSchema’
src/sqlite4.c:84255: warning: unused variable ‘pTab’
src/sqlite4.c: At top level:
src/sqlite4.c:91057: error: redefinition of typedef ‘WhereLevel’
src/sqlite4.c:5445: note: previous declaration of ‘WhereLevel’ was here
src/sqlite4.c: In function ‘codeOneLoopStart’:
src/sqlite4.c:94356: warning: unused variable ‘iRowidReg’
src/sqlite4.c: In function ‘sqlite4_mi_column_value’:
src/sqlite4.c:100099: warning: unused variable ‘nData’
src/sqlite4.c:100099: warning: unused variable ‘aData’
*_error: command 'gcc' failed with exit status 1**

**Comment by abeusher** [comment]
I got it to build successfully using these instructions for upgrading gcc on Centos 6.x:
http://ask.xmodulo.com/upgrade-gcc-centos.html

Then I switched to the new gcc:
**scl enable devtoolset-1.1 bash**

and tried 
**python setup.py build**

yielding success.

**Comment by coleifer** [comment]
Thanks for the report on how to fix. I think this issue falls under either Centos or SQLite4. Also, that centos is about 4 years old...
