### ISSUE TITLE
Seg faulting on keys()?

### ISSUE THREAD

**Issue by shguan10** [coleifer/python-lsm-db#15]
The code I have is 
```
import lsm
dbcon = lsm.LSM('data_config.db')
[ _ for _ in dbcon.keys()]
```
upon which it segfaults. That is the only error message.

I am running Ubuntu 14.04.

Any help would be appreciated!

**Comment by coleifer** [comment]
Is there data stored in that database, or is it empty? What Python version?

**Comment by coleifer** [comment]
```
In [1]: from lsm import LSM

In [2]: l = LSM('/tmp/foo.lsm')

In [3]: [x for x in l.keys()]
Out[3]: []
```

Also:

```python
In [4]: l['k1'] = 'v1'

In [5]: l['k2'] = 'v2'

In [6]: l.close()
Out[6]: True

In [7]: l = LSM('/tmp/foo.lsm')

In [8]: [x for x in l.keys()]
Out[8]: ['k1', 'k2']

```

**Comment by shguan10** [comment]
Thank you for responding. 

I am using python 2.7; the demo commands you sent me seem to work fine.

In addition, when I copy my database from the shared directory to a personal directory, I can read the database fine. But it still segfaults when I try it in the shared directory, even though the file permissions look the same!

**Comment by coleifer** [comment]
I'm not sure what a shared directory is...but perhaps problems between the virtual file API of LSM and the underlying storage driver?

**Comment by shguan10** [comment]
I am in a research lab, where we use one server. There is a giant database file (~70Gb) in a shared directory (usually its /shared/shared which is readable by any user) so we won't have to have a separate copy of the giant database in each of our personal directories (for example in /home/$WHOAMI). 

It would be swell for sqlite4 to support opening files from the shared directory! Otherwise for each new update to the giant database, we would have to copy it from the shared directory to our personal directory again, which is a time-consuming and space-inefficient process.

Thank you for your time!

**Comment by coleifer** [comment]
I should have been more clear... is that an NFS mount, samba share, something else? Are you developing on linux? My guess is that the VFS is running into issues with the storage driver. This is not the sqlite4 project but only a python binding for some c libraries, so the change would need to happen upstream.

**Comment by shguan10** [comment]
I am using Ubuntu 16.04, and am ssh-ing into the server which is running Ubuntu 14.04. Let me check how the shared directory is mounted, but it is my understanding that it is located physically on hard disk.

**Comment by shguan10** [comment]
My adviser has confirmed that the shared directory is local on hard disk. Are there any work-arounds/solutions that you can think of for my problem? Thank you!

**Comment by coleifer** [comment]
If you can provide a small data-set that would allow me to replicate the issue, I can spend some time trying to debug it, but without any way to replicate I don't have any other ideas.

**Comment by coleifer** [comment]
Of course if you are familiar with gdb you can probably get a backtrace, and see what's causing the segfault?
