### ISSUE TITLE
Sqlite4 development finished, is there any problem on using this?

### ISSUE THREAD

**Issue by namuyan** [coleifer/python-lsm-db#16]
I want to Key-Value database for my project, I select Leveldb first.
But Leveldb is very very simple for usage, no transaction, only one connection allowed, no cursor and difficulty on install for win (require users).
I know this lib good, I want to use this.
But I hear Sqlite4 development finished (no people develop?), is there any problem on using this?
Thanks!

Source:
https://sqlite.org/src4/brlist
https://news.ycombinator.com/item?id=15648280

**Comment by coleifer** [comment]
This library now uses sources from sqlite3 (ext/lsm1):

https://www.sqlite.org/cgi/src/dir?ci=16db73842ade5eb0&name=ext/lsm1

So the code is originally from sqlite4 but has been brought into sqlite3 and is being actively maintained as an extension.
