### ISSUE TITLE
Configurable encoding/decoding

### ISSUE THREAD

**Issue by invisiblefunnel** [coleifer/python-lsm-db#17]
Hi @coleifer, thanks for the excellent package. This seems to be the best approach to a simple, on-disk key/value store in Python.

I usually find myself defining custom functions to `encode`/`decode` values. To ensure consistent use of those functions I often create a subclass and override specific methods. Have you found this to be the case in your experience? Is there a pattern other than inheritance you use to achieve the same outcome? A wrapper object?

Would you consider extending the `LSM` class to accept optional encode/decode functions, similar to [`sqlitedict`](https://github.com/RaRe-Technologies/sqlitedict/blob/f5c57f1f833e251b8ffe2e63642d4923b52646cd/README.rst#features)?

I appreciate your consideration of this feature request and I'm happy to put together a pull request if you're interested in making this change.

**Comment by mosquito** [comment]
I wrote https://pypi.org/project/lsm-db-extras/ for similar cases.

**Comment by invisiblefunnel** [comment]
@mosquito thanks! That looks like a great package. You've added some nice features. It looks like much of the code in `lsm-db-extras` could be simplified if `lsm-db` accepted custom encode/decode functions. Are you also interested in seeing this feature implemented?

**Comment by coleifer** [comment]
It's just a thin layer on top of the C APIs exported by the library itself. Although the LSM implementations primary author tends to merge fixes, it's not really widely-deployed or used by many people. So, unless you really know what you're doing, I think this is kinda a niche library.

I'd probably recommend using sqlite as a key/value store. Other tools like lmdb, leveldb, etc., really require some expertise to use correctly, and lsm-db is not really an exception.
