### ISSUE TITLE
How to Dumps the Key-Value Faster?

### ISSUE THREAD

**Issue by Yummy26** [coleifer/python-lsm-db#18]
As the document says, python-lsm provides iterator for get the key-value data. But iterate the whole db and write k-v into file sure would be un-efficient, as we know lsm stores the key-value data into sorted strings makes it possible to write to files by multi-processes.

**Comment by coleifer** [comment]
What?

Just copy the file using `cp` if you want a copy.

**Comment by Yummy26** [comment]
i mean the file need to be decode to human readable two columns table file, or csv file.

how `cp` works?

**Comment by coleifer** [comment]
Oh, in that case you can use the cursor interface, iterate over the db instance itself, etc, etc.

https://lsm-db.readthedocs.io/en/latest/api.html#lsm.LSM.__iter__

https://lsm-db.readthedocs.io/en/latest/api.html#lsm.LSM.cursor
