### ISSUE TITLE
Cython-less installation is missing `lsm.c`

### ISSUE THREAD

**Issue by fonsocarre** [coleifer/python-lsm-db#22]
Hi, @coleifer. First thanks for putting this together. It is a lifesaver!
I have been struggling with the installation if I do `pip install lsm-db --no-deps`. Without `Cython`, the setup script looks for the Cython-generated `lsm.c` file, but it is not in the repo. I understand it is a bit of a hack to have the generated c code in the repo, but it would make people's lives much easier. Maybe we can add a warning when setting up without Cython, but allowing it? 
In any case, I have the Cython-generated code already in my fork of the repo, so happy to start a PR and include it if you are ok with it.

**Comment by fonsocarre** [comment]
Closing this. I see there are `lsm.c` files distributed in PyPI. They are just old.

**Comment by mosquito** [comment]
@fonsocarre I once wrote an alternative implementation of this in C, you can try it if you want https://pypi.org/project/lsm/

**Comment by fonsocarre** [comment]
Thanks @mosquito appreciate it. I’ll have a look.
