### ISSUE TITLE
How sqlite4 source was produced (and how to upgrade it)?

### ISSUE THREAD

**Issue by pfalcon** [coleifer/python-lsm-db#5]
In http://charlesleifer.com/blog/using-sqlite4-s-lsm-storage-engine-as-a-stand-alone-nosql-database-with-python/ , you link to http://sqlite.org/src4/tree?ci=trunk ("After pulling down the SQLite4 source code"), but what's there is nice broken-down source files, whereas this repository contains amalgamation. Why so? Do you take care to build with -ffunction-sections/--gc-sections to remove unneeded cruft?

Generally, there's veil of mystery surrounding sqlite4. Porject started in some 2011, and still largely unknown (I keep an eye on embedded database space and I manage to miss until now). Then if you wade thru messy NIH fossil stuff, you will find that trunk doesn't even compile. That's so different from cheerful articles telling "sqlite4 is here, we can use it". So, it would be very nice if you tried to break this circle, and provide instructions how to get a working sqlite4 code for this project (so people can upgrade to a newer version, verify that you didn't put backdoors in it, etc.)

**Comment by coleifer** [comment]
you've got a horrible attitude. go away please.

**Comment by coleifer** [comment]
The makefile for the project contains targets for `sqlite4.c` which, when run, generate the amalgamation. The amalgamation exists for a reason, one of which is to be easily portable and easy to embed in projects. This project uses it as an embedded library. So yes, I use the amalgamation.

Also you are just straight wrong, **trunk compiles just fine**. I just pulled it down to be sure from fossil and built working binary/library.

Oh and again, you have a HORRIBLE attitude.

**Comment by coleifer** [comment]
I've edited the post with instructions on building and my opinion on the state of sqlite4.

http://charlesleifer.com/blog/using-sqlite4-s-lsm-storage-engine-as-a-stand-alone-nosql-database-with-python/#note-on-sqlite4
