### ISSUE TITLE
bytes API on Python 3

### ISSUE THREAD

**Issue by pitrou** [coleifer/python-lsm-db#8]
I'm surprised that `lsm` uses unicode strings for keys and values on Python 3. I would have expected a bytes-based API. Perhaps this should at least be made possible as an option?

**Comment by coleifer** [comment]
I hear you, it'd be much easier for me to just require everyone to pass in UTF-8 encoded bytes, but remember this is Python and people want their unicode and they don't want to think about it :)

**Comment by pitrou** [comment]
Unicode strings are the right type for data which is obviously textual, but keys and values in a key-value store don't have to be textual. For example, I may store pickled Python objects as values: what sense does it make to pass those as text? (by decoding to `latin1`, presumably)

Another point is that the encoding or decoding step adds performance overhead, which is a waste when the user has to undo that step because their keys and values are really bytes :-)

**Comment by coleifer** [comment]
Dude I hear you. Ok I'm convinced, fuck Unicode support, ppl are just going to have to encode it themselves

**Comment by coleifer** [comment]
Fixed in 0.4.0.
