### ISSUE TITLE
Random patches

### ISSUE THREAD

**Issue by jeffsenn** [coleifer/python-lsm-db#9]
Here are a couple of tiny patches to fix 1) a problem with an 'assert' in lsmStringExtend for an edge case when debugging is enabled and 2) an uninitialized variable warning (and theoretical problem).

[patch1.txt](https://github.com/coleifer/python-lsm-db/files/688283/patch1.txt)

**Comment by coleifer** [comment]
Nice! That's actually the SQLite4 code-base. Do you mind opening a pull-request? That's kinda the best way in terms of the github UI.
